### PR TITLE
Fixed CodeResolveAndExportTest

### PR DESCRIPTION
**Pull request by amol-wani-elimu**
Updated CodeResolveAndExportTest as it was failing sometime as inputstream not closing everytime.

### CODE REVIEW

**Comment by amol-wani-elimu** [comment]
Hi @kaicode,
Added small update for CodeResolveAndExportTest, as it was failing uncertainly due to inputstream not getting closed.

**Comment by kaicode** [comment]
Thanks @amol-wani-elimu, the commit made on the branch `ValueSetUrlSupport` is visible in the pull request 
https://github.com/synthetichealth/synthea/pull/758 please see my comments about fixing the whitespace. This pull request seems to contain a different commit without the whitespace problem? Could I take that and replace the commit with incorrect whitespace using interactive rebase?

**Comment by amol-wani-elimu** [comment]
Hi @kaicode,
due to this whitespace issue I have created new branch and pushed code changes on it, I am not seeing permission to delete that branch, so new changes are on ValueSetUrlSupport_fix branch.

**Comment by kaicode** [comment]
No problem. I will move this commit into the branch with the pull request, replacing the whitespace issue.
Thank you.

**Comment by amol-wani-elimu** [comment]
Thank you @kaicode, I understood what you was saying after looking into synthetichealth#758, my changes with whitespace got reflected there in actual synthea pull request.

**Comment by kaicode** [comment]
I force pushed this commit into the other branch. Your good version of this is now in the pull request. Cheers.

**Pull request merged**
