### PR TITLE
Value set url support

### PR DESCRIPTION
**Pull request by amolht**
1. This code supporting valueset support in patient generation.
2. In valueset URI we can add all different kinds of ECL expression, ECL expression with filters, isa and refset expressions.

### CODE REVIEW

**Review by kaicode — CHANGES_REQUESTED** [review]
Hi @amolht this looks good on the whole. 

I can see you replaced the TerminologyClient with a Spring RestTemplate, did the TerminologyClient not support ECL with filtering?

It looks like some of the unit tests make calls out to a live service? This is not best practice because changes to the content or availability of the service could cause the project build to break. It looks like Jon had this mocked previously. Please use mocking.

It looks like there is now no limit to the number of value sets cached during data generation but this seems okay to me.

**Comment by amolht** [comment]
> Hi @amolht this looks good on the whole.
> 
> I can see you replaced the TerminologyClient with a Spring RestTemplate, did the TerminologyClient not support ECL with filtering?
> @kaicode yes you are right TerminologyClient is not supporting ECL filtering, thats why we need to select Spring RestTemplate approach.

> It looks like some of the unit tests make calls out to a live service? This is not best practice because changes to the content or availability of the service could cause the project build to break. It looks like Jon had this mocked previously. Please use mocking.
> My bad, I will revisit those unit testcases and will update to fetch data from mock only.

> It looks like there is now no limit to the number of value sets cached during data generation but this seems okay to me.
> Previously they were trying to pull 1000 and getting random code from that, and for next patient next 1000 and getting random code from that. So this approach is causing multiple times it is giving a call to FIHR server. Now what we have done is that in single go we retrieving codes and from that, we are getting code for the patient.

**Comment by amolht** [comment]
Hi @kaicode,
* Updated code for getting wiremock response for ValueSetCodeResolverTest and CodeResolveAndExportTest
* To stub response from wiremock we have made some changes in mappings .json files(as we are using now RestTemplate to fetch Valueset response) for ValueSetCodeResolverTest and CodeResolveAndExportTest tests as follows
 - Replaced "url" with "urlPath" : as we need to match part of url
 - Replaced "POST" with "GET"    : as all RestTemplate request is GET
 - Used "queryParameters" property : to make exact match 
 - Removed "bodyPatterns" : as we are not using "count" and "offset" while fetching response from terminology client url 
 - Removed redundant mappings files, almost 60+ jsons deleted.

**Review by kaicode — APPROVED** [review]
@amolht thank you for the explanation of your approach and for making the requested changes.
This looks good to me now 👍

**Pull request merged**
